/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CAKEmanagement;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2-getWidth()/2,size.height/2-getHeight()/2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Pas = new javax.swing.JLabel();
        passs = new javax.swing.JPasswordField();
        aa = new javax.swing.JTextField();
        jButton1_regi = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1_regi1 = new javax.swing.JButton();
        showpass = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 255, 204));
        jLabel2.setFont(new java.awt.Font("STCaiyun", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sign In");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 300, 50));

        Name.setBackground(new java.awt.Color(102, 102, 0));
        Name.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Username");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 120, -1));

        Pas.setBackground(new java.awt.Color(102, 102, 0));
        Pas.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Pas.setForeground(new java.awt.Color(255, 255, 255));
        Pas.setText("Password");
        getContentPane().add(Pas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 120, -1));

        passs.setBackground(new java.awt.Color(204, 255, 204));
        passs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passsActionPerformed(evt);
            }
        });
        getContentPane().add(passs, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 330, 30));

        aa.setBackground(new java.awt.Color(204, 255, 204));
        aa.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        aa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aaKeyReleased(evt);
            }
        });
        getContentPane().add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 330, 30));

        jButton1_regi.setBackground(new java.awt.Color(0, 204, 0));
        jButton1_regi.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jButton1_regi.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_regi.setText("Sign In");
        jButton1_regi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_regi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_regiActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_regi, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 120, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Click here for new account!");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 219, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Forget Password?");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 157, -1));

        jButton1_regi1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1_regi1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jButton1_regi1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_regi1.setText("Cancle");
        jButton1_regi1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1_regi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_regi1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_regi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 120, -1));

        showpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        showpass.setText("Show password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        getContentPane().add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/photo-1542826438-bd32f43d626f_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_passsActionPerformed

    private void aaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aaKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_aaKeyReleased

    private void jButton1_regiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_regiActionPerformed

        PreparedStatement ps;
        ResultSet rs;
        String name = aa.getText();
        String pass = String.valueOf(passs.getPassword());
       
        String q="SELECT * FROM `user` WHERE `Username`=? AND`Password`=?";
        try{
        ps = Myconnection.mycon().prepareStatement(q);
        ps.setString(1, name);
        ps.setString(2,pass);
        rs = ps.executeQuery();
        if(rs.next()){
            JOptionPane.showMessageDialog(null,"Thanks for logIn");
            UDB m=new UDB();
            m.setVisible(true);
            m.pack();
            m.setLocationRelativeTo(null);
            m.setExtendedState(JFrame.MAXIMIZED_BOTH);
            m.jLabel20.setText(name);
            m.jLabel181.setText(name);
          
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Incorrect username or password");

        }
        }catch(SQLException ex){
            Logger.getLogger(registration.class.getName()).log(Level.SEVERE, null, ex);
            
        }
 
    }//GEN-LAST:event_jButton1_regiActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        registration p=new registration();
        p.setVisible(true);
        p.pack();
        p.setLocationRelativeTo(null);
        p.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1_regi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_regi1ActionPerformed
        // TODO add your handling code here:
        JFrame frame =new JFrame("Cancle");
        if(JOptionPane.showConfirmDialog(frame,"Do you want to cancel?","Cancle",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1_regi1ActionPerformed

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        // TODO add your handling code here:
        if(showpass.isSelected()){
            passs.setEchoChar((char)0);}
        else
        {
            passs.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        ForgetPass p=new ForgetPass();
        p.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Pas;
    private javax.swing.JTextField aa;
    private javax.swing.JButton jButton1_regi;
    private javax.swing.JButton jButton1_regi1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passs;
    private javax.swing.JCheckBox showpass;
    // End of variables declaration//GEN-END:variables
}
